From owner-alumni@CS.UTK.EDU Mon May  3 14:13:22 1999
Return-Path: <owner-alumni@CS.UTK.EDU>
Received: from localhost (marvin@localhost) 
        by CS.UTK.EDU with SMTP (cf v2.9s-UTK)
	id OAA09772; Mon, 3 May 1999 14:03:00 -0400 (EDT)
Errors-to: owner-alumni@CS.UTK.EDU
Received: from galoob.cs.utk.edu (LOCALHOST.cs.utk.edu [127.0.0.1]) 
        by CS.UTK.EDU with ESMTP (cf v2.9s-UTK)
	id OAA09763; Mon, 3 May 1999 14:02:58 -0400 (EDT)
Received: from galoob.cs.utk.edu (128.169.94.219 -> GALOOB.CS.UTK.EDU)
 by CS.UTK.EDU (smtpshim v1.0); Mon, 3 May 1999 14:02:58 -0400
Received: from cs.utk.edu (localhost [127.0.0.1])
	by galoob.cs.utk.edu (cf v3.2) with ESMTP id OAA13563;
	Mon, 3 May 1999 14:02:43 -0400 (EDT)
Message-Id: <199905031802.OAA13563@galoob.cs.utk.edu>
X-Mailer: exmh version 2.0.2 2/24/98
X-To: grad-student@cs.utk.edu, undergrad@cs.utk.edu, alumni@cs.utk.edu
Subject: Job oppt at CTI in West Knoxville
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Date: Mon, 03 May 1999 14:02:42 -0400
From: Donna E Bodenheimer <bodenhei@CS.UTK.EDU>
To: alumni-list:;
Status: R


-----
=======================================================================

JOB OPPORTUNITY:


CTI in West Knoxville is trying to fill two positions.

1. Full-time Lotus Notes Developer
- -Notes experience is not required but would be helpful.
- -If no Notes experience then experience with Visual Basic or other similar
programming environments.
- -If no VB or similar experience then must be a creative, energetic and
sharp programmer.
- -Other skills such as knowledge of networking technologies, PC
software/troubleshooting - basically, the more well-rounded the better.
- -Salary commensurate with experience.

2. Intern/Co-op/Part-Time for Web development/support using Lotus Notes.
- -Similar requirements as above. Someone with web development experience and
strong programming skills would be a strong candidate.
- -The hours for this position are very flexible and would be ideal as a
summer job for a student that would be interested in continuing to work
part-time next fall .

You can find out more about CTI at http://www.cti-pet.com

If anyone would like more information or would like to submit a resume have
them contact:

Mary Lou DuBois
IT Manager
mary.lou.dubois@cti-pet.com

or,

Scott Hitch
scott.hitch@cti-pet.com





-- 
********************************************************************

Donna E. Bodenheimer, CPS                       bodenhei@cs.utk.edu
Computer Science Department                    Phone: 423/974-0995
The University of Tennessee                        FAX: 423/974-4404
107 Ayres Hall
Knoxville, TN  37996-1301 

********************************************************************







