#!/usr/local/bin/perl  -w
#file: iceCr
#from page 190 Learning Pearl

use strict; #enforce variable declarations and quoting
use CGI qw(:standard);

print header, start_html("Ice Cream Stand"), h1("Ice Cream Stand");
if(param()) {#the form has already been filled out
	my $who = param("name");
	my $flavor = param("flavor");
	my $scoops = param("scoops");
	my $taxrate = 1.085;
	my $cost = sprintf(" %.2f", $taxrate * ( 1.00 + $scoops * 0.25));
	print p("OK, $who, have $scoops scoops of $flavor for \$$cost.");
        }
else { #first time through so present clean form
	print hr();
	print start_form();
	print p("What's your name?  ", textfield("name"));
	print p("Select a flavor: ", 
                 popup_menu("flavor",
                 ['mint','cherry','coffee']));
	print p("How many scoops? ", 
 		 popup_menu("scoops",
		 [1..3]));			
 	print p(submit("order"), reset("clear"));
	print end_form(), hr();
	}
print end_html;

